name: voice-to-text
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - runpod
    - stable-ts==2.18.3
    - requests
    - torch>=2.4.1
    - torchvision
    - torchaudio 